services:
  mongodb:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - mongodbnet
networks:
  mongodbnet:
    name: mongodbnet
    external: false
